doctrine:
  orm:
    mappings:
      PrettyBlocks:
        type: annotation
        dir: '%kernel.project_dir%/modules/prettyblocks/src/Entity'
        prefix: 'PrestaSafe\PrettyBlocks\Entity'
        is_bundle: false

services:
  _defaults:
    public: true
    autoconfigure: true
    autowire: true

  # Registry for dynamically registering entity types
  PrestaSafe\PrettyBlocks\Registry\ElementRegistry:
    class: PrestaSafe\PrettyBlocks\Registry\ElementRegistry

  # Factory for dynamic entity creation
  PrestaSafe\PrettyBlocks\Factory\EntityFactory:
    class: PrestaSafe\PrettyBlocks\Factory\EntityFactory
    arguments:
      - '@PrestaSafe\PrettyBlocks\Registry\ElementRegistry'

  # Doctrine Repositories
  PrestaSafe\PrettyBlocks\Repository\BlockRepository:
    class: PrestaSafe\PrettyBlocks\Repository\BlockRepository
    factory: [ '@doctrine.orm.entity_manager', getRepository ]
    arguments:
      -
        $persistentObject: PrestaSafe\PrettyBlocks\Entity\Block

  PrestaSafe\PrettyBlocks\Repository\ComponentRepository:
    class: PrestaSafe\PrettyBlocks\Repository\ComponentRepository
    factory: [ '@doctrine.orm.entity_manager', getRepository ]
    arguments:
      -
        $persistentObject: PrestaSafe\PrettyBlocks\Entity\Component

  PrestaSafe\PrettyBlocks\Repository\PrimitiveFieldRepository:
    class: PrestaSafe\PrettyBlocks\Repository\PrimitiveFieldRepository
    factory: [ '@doctrine.orm.entity_manager', getRepository ]
    arguments:
      -
        $persistentObject: PrestaSafe\PrettyBlocks\Entity\PrimitiveField

  PrestaSafe\PrettyBlocks\Repository\ZoneRepository:
    class: PrestaSafe\PrettyBlocks\Repository\ZoneRepository
    factory: [ '@doctrine.orm.entity_manager', getRepository ]
    arguments:
      - 'PrestaSafe\PrettyBlocks\Entity\Zone'

  # Main service for managing zones
  PrestaSafe\PrettyBlocks\Service\ZoneService:
    class: PrestaSafe\PrettyBlocks\Service\ZoneService
    arguments:
      - '@PrestaSafe\PrettyBlocks\Repository\ZoneRepository'
      - '@doctrine.orm.entity_manager'

  # API Controllers
  PrestaSafe\PrettyBlocks\Controller\Api\ZoneController:
    class: PrestaSafe\PrettyBlocks\Controller\Api\ZoneController
    arguments:
      - '@PrestaSafe\PrettyBlocks\Service\ZoneService'
    tags:
      - { name: controller.service_arguments }
